"use client";
import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { Area, Bar, BarChart, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, ArrowDown, ArrowRight, ArrowUp, Bike, ChevronDown, GraduationCap, House, Info, Pause, Play, RefreshCw, RotateCcw } from "lucide-react";
import SiteHeader from "@/components/SiteHeader";
import CitySelector from "@/components/dashboard/CitySelector";
import WindCompass from "@/components/weather/WindCompass";
import { getAQICategory, getCategoryHex, getCategoryTone } from "@/lib/aqi";
import { analyzeDrivers, findBestWindow, findFastestChange, findWorstWindow, getActivityPlan, getDispersion, getDominantPollutant, selectHours, sortPollutants } from "./analysis";
import type { AtmosphericDataset, AtmosphericHour, CityName, PollutantKey } from "./types";

const CORE: PollutantKey[] = ["pm2_5","pm10","ozone","nitrogen_dioxide","carbon_monoxide","sulphur_dioxide"];
const COLORS: Record<string,string> = { aqi:"#f4f7f7", pm2_5:"#36d399", pm10:"#fbbf24", nitrogen_dioxide:"#60a5fa", ozone:"#a78bfa", carbon_monoxide:"#fb7185", sulphur_dioxide:"#22d3ee" };
const LABELS: Record<string,string> = { aqi:"AQI", pm2_5:"PM2.5",pm10:"PM10",nitrogen_dioxide:"NO₂",ozone:"O₃",carbon_monoxide:"CO",sulphur_dioxide:"SO₂" };
const num = (v:number|null|undefined,d=0) => v == null || !Number.isFinite(v) ? "—" : v.toFixed(d);
const time = (s:string) => s.slice(11,16);
const shortDate = (s:string) => new Intl.DateTimeFormat("en-PK",{weekday:"short",day:"numeric",month:"short"}).format(new Date(`${s}:00+05:00`));
const trend = (hours:AtmosphericHour[]) => { const a=hours[0]?.aqi,b=hours[Math.min(5,hours.length-1)]?.aqi; if(a==null||b==null||Math.abs(b-a)<=3)return {text:"Stable",icon:ArrowRight,cls:"stable"}; return b>a?{text:"Worsening",icon:ArrowUp,cls:"worse"}:{text:"Improving",icon:ArrowDown,cls:"better"}; };
const chartRows = (hours:AtmosphericHour[]) => hours.map((h,i)=>({ ...h, label:i===0?"NOW":time(h.time), pm2_5:h.pollutants.pm2_5?.concentration,pm10:h.pollutants.pm10?.concentration,nitrogen_dioxide:h.pollutants.nitrogen_dioxide?.concentration,ozone:h.pollutants.ozone?.concentration,carbon_monoxide:h.pollutants.carbon_monoxide?.concentration,sulphur_dioxide:h.pollutants.sulphur_dioxide?.concentration }));
function RangeToggle({value,onChange}:{value:24|48|72,onChange:(v:24|48|72)=>void}) { return <div className="ai-range">{([24,48,72] as const).map(v=><button key={v} aria-pressed={v===value} onClick={()=>onChange(v)}>{v}H</button>)}</div>; }
function WindowCard({title,result,accent}:{title:string,result:ReturnType<typeof findBestWindow>,accent:string}) { if(!result)return null; return <article className="ai-window-card" style={{"--window-accent":accent} as React.CSSProperties}><p className="eyebrow">{title}</p><h3>{shortDate(result.hours[0].time)}</h3><strong>{time(result.hours[0].time)} – {time(result.hours.at(-1)!.time)}</strong><div className="ai-window-aqi"><span>Expected AQI</span><b>{result.min}–{result.max}</b></div></article>; }

export default function AtmosphericIntelligence({initialData}:{initialData:AtmosphericDataset}) {
  const [city,setCity]=useState<CityName>("Karachi"),[range,setRange]=useState<24|48|72>(72),[selected,setSelected]=useState(0),[method,setMethod]=useState(false),[playing,setPlaying]=useState(false);
  const [enabled,setEnabled]=useState<Set<string>>(new Set(["aqi","pm2_5","pm10"]));
  const cityData=initialData.cities.find(c=>c.city===city)??initialData.cities[0];
  const hours=useMemo(()=>selectHours(cityData?.hours??[],range),[cityData,range]); const now=hours[selected]??hours[0];
  const core=CORE.map(k=>now?.pollutants[k]).filter(Boolean) as NonNullable<typeof now>["pollutants"][PollutantKey][];
  const ranked=sortPollutants(core.filter(Boolean) as any); const dominant=getDominantPollutant(ranked); const move=trend(hours); const TrendIcon=move.icon;
  const best=findBestWindow((cityData?.hours??[]).slice(0,72)),worst=findWorstWindow((cityData?.hours??[]).slice(0,72));
  const improve=findFastestChange((cityData?.hours??[]).slice(0,72),"improvement"),worsen=findFastestChange((cityData?.hours??[]).slice(0,72),"deterioration");
  const drivers=analyzeDrivers(hours),rows=chartRows(hours),category=now?.aqi!=null?getAQICategory(now.aqi):"Unavailable",tone=category!=="Unavailable"?getCategoryTone(category):"neutral";
  const activities=getActivityPlan(now);
  useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setSelected(i=>{if(i>=hours.length-1){setPlaying(false);return i}return i+1}),1100);return()=>window.clearInterval(timer)},[playing,hours.length]);
  useEffect(()=>{if(selected<hours.length)return;const timer=window.setTimeout(()=>setSelected(Math.max(0,hours.length-1)),0);return()=>window.clearTimeout(timer)},[hours.length,selected]);
  if(!cityData) return <main><SiteHeader/><div className="ai-shell ai-error"><h1>Atmospheric data temporarily unavailable.</h1><button className="btn-primary" onClick={()=>location.reload()}><RefreshCw size={15}/> Retry</button></div></main>;
  const chooseCity=(v:string)=>{setCity(v as CityName);setSelected(0);history.replaceState(null,"",`/atmospheric-intelligence?city=${v}`)};
  return <main><SiteHeader/><div className="ai-shell">
    <header className="ai-page-head"><div><p className="eyebrow">Open-Meteo forecast intelligence · {cityData.timezone}</p><h1>Atmospheric <em>Intelligence</em></h1><p>What controls the air now—and where it is heading over the next 72 hours.</p></div><div className="ai-head-controls"><CitySelector cities={["Karachi","Lahore","Islamabad"]} activeCity={cityData.city} onSelectCity={chooseCity}/><span>Retrieved {new Date(initialData.retrievedAt).toLocaleTimeString("en-PK",{hour:"2-digit",minute:"2-digit"})}</span></div></header>
    <AnimatePresence mode="wait"><motion.div key={cityData.city} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.35}}>
      <section className="ai-playback" aria-label="Forecast playback"><div><span className="eyebrow">Forecast playback</span><strong>{shortDate(now.time)} · {time(now.time)}</strong><em>Hour {selected+1} of {hours.length}</em></div><div className="ai-playback-track"><motion.i animate={{width:`${hours.length>1?(selected/(hours.length-1))*100:0}%`}} transition={{duration:.25}}/><input aria-label="Forecast hour" type="range" min="0" max={Math.max(0,hours.length-1)} value={selected} onChange={e=>{setPlaying(false);setSelected(Number(e.target.value))}}/></div><div className="ai-playback-actions"><button title="Restart" onClick={()=>{setPlaying(false);setSelected(0)}}><RotateCcw size={16}/></button><button className="primary" onClick={()=>{if(selected>=hours.length-1)setSelected(0);setPlaying(v=>!v)}}>{playing?<Pause size={17}/>:<Play size={17}/>} {playing?"Pause":"Play"}</button><RangeToggle value={range} onChange={v=>{setPlaying(false);setRange(v)}}/></div></section>
      <section className="ai-hero">
        <div className="ai-hero-copy"><p className="eyebrow">Pollution fingerprint · current forecast hour</p><div className="ai-aqi-line"><motion.strong key={now?.aqi} initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}}>{num(now?.aqi)}</motion.strong><div><span className={`badge ${tone}`}><i className="badge-dot"/>{category}</span><p>U.S. AQI</p></div></div><div className="ai-dominant"><span>Dominant pollutant</span><h2>{dominant?.label??"Unavailable"}</h2><p>{num(dominant?.concentration,1)} {dominant?.unit} <b>· AQI {num(dominant?.aqi)}</b></p></div><div className={`ai-trend ${move.cls}`}><TrendIcon size={18}/><b>{move.text}</b><span>next six hours</span></div></div>
        <div className="ai-fingerprint" aria-label="Relative pollutant pressure"><ResponsiveContainer width="100%" height={360}><BarChart data={ranked} layout="vertical" margin={{left:10,right:24}}><CartesianGrid horizontal={false} stroke="rgba(255,255,255,.06)"/><XAxis type="number" domain={[0,"dataMax + 20"]} hide/><YAxis type="category" dataKey="label" width={48} tick={{fill:"#8fa8ad",fontSize:12}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#0b1417",border:"1px solid rgba(255,255,255,.12)"}} formatter={(v)=>[v,"Pollutant AQI"]}/><Bar dataKey="aqi" fill={now?.aqi!=null?getCategoryHex(getAQICategory(now.aqi)):"#36d399"} radius={[0,3,3,0]} animationDuration={700}/></BarChart></ResponsiveContainer><p>Bars compare pollutant-specific U.S. AQI—not raw concentrations.</p></div>
      </section>
      <section className="ai-section"><div className="ai-section-head"><div><p className="eyebrow">Current pollutant ranking</p><h2>Relative pollutant pressure</h2></div></div><div className="ai-ranking">{ranked.map((p,i)=>{const t=trend((cityData.hours??[]).slice(0,6).map(h=>({...h,aqi:h.pollutants[p.key]?.aqi??null})));return <motion.div layout key={p.key} className="ai-rank-row"><b>0{i+1}</b><strong>{p.label}</strong><span>{num(p.concentration,1)} {p.unit}</span><span className="tabular">AQI {num(p.aqi)}</span><span>{p.aqi!=null?getAQICategory(p.aqi):"Unavailable"}</span><em className={t.cls}>{t.text}</em></motion.div>})}</div></section>
      <section className="ai-section"><div className="ai-section-head"><div><p className="eyebrow">Pollution timeline</p><h2>72-hour pollutant evolution</h2></div><RangeToggle value={range} onChange={setRange}/></div><div className="ai-toggles">{Object.keys(COLORS).map(k=><button key={k} aria-pressed={enabled.has(k)} style={{"--series":COLORS[k]} as React.CSSProperties} onClick={()=>setEnabled(s=>{const n=new Set(s);if(n.has(k))n.delete(k);else n.add(k);return n})}>{LABELS[k]}</button>)}</div><div className="ai-chart"><ResponsiveContainer width="100%" height={360}><ComposedChart data={rows} onMouseMove={(s:any)=>s?.activeTooltipIndex!=null&&setSelected(s.activeTooltipIndex)}><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="label" minTickGap={35} tick={{fill:"#576b70",fontSize:10}}/><YAxis tick={{fill:"#576b70",fontSize:10}} axisLine={false}/><Tooltip contentStyle={{background:"#081115",border:"1px solid rgba(255,255,255,.14)"}} labelFormatter={(_,p)=>p?.[0]?.payload?.time?.replace("T"," ")}/>{Object.keys(COLORS).filter(k=>enabled.has(k)).map(k=><Line key={k} type="monotone" dataKey={k} stroke={COLORS[k]} dot={false} strokeWidth={k==="aqi"?3:2} connectNulls={false}/>)}</ComposedChart></ResponsiveContainer></div></section>
      <section className="ai-section ai-drivers"><div className="ai-section-head"><div><p className="eyebrow">Atmospheric drivers</p><h2>Why is the air changing?</h2></div><span className="ai-dispersion">Dispersion <b>{getDispersion(now)}</b><i title="This is a simplified indicator derived from Open-Meteo weather conditions and is not an official air-quality index."><Info size={13}/></i></span></div><div className="ai-driver-grid">{drivers.map((d,i)=><motion.article key={d.id} initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.07}} className={`ai-driver ${d.tone}`}><span>{String(i+1).padStart(2,"0")}</span><h3>{d.title}</h3><p>{d.explanation}</p></motion.article>)}</div><div className="ai-weather-rail"><WindCompass directionDegrees={now.windDirection} speedKmh={now.windSpeed}/><div><span>Gusts</span><b>{num(now.windGusts,1)} km/h</b></div><div><span>Humidity</span><b>{num(now.humidity)}%</b></div><div><span>Rain</span><b>{num(now.rain,1)} mm</b></div><div><span>Visibility</span><b>{now.visibility!=null?`${num(now.visibility/1000,1)} km`:"—"}</b></div></div>
        <div className="ai-chart ai-sync"><ResponsiveContainer width="100%" height={390}><ComposedChart data={rows} syncId="atmosphere" onMouseMove={(s:any)=>s?.activeTooltipIndex!=null&&setSelected(s.activeTooltipIndex)}><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="label" minTickGap={35} tick={{fill:"#576b70",fontSize:10}}/><YAxis yAxisId="air" tick={{fill:"#576b70",fontSize:10}}/><YAxis yAxisId="weather" orientation="right" tick={{fill:"#576b70",fontSize:10}}/><Tooltip contentStyle={{background:"#081115",border:"1px solid rgba(255,255,255,.14)"}}/><Area yAxisId="air" dataKey="aqi" stroke="#fb7185" fill="rgba(251,113,133,.1)"/><Line yAxisId="air" dataKey="pm2_5" stroke="#36d399" dot={false}/><Line yAxisId="weather" dataKey="windSpeed" stroke="#60a5fa" dot={false}/><Line yAxisId="weather" dataKey="humidity" stroke="#a78bfa" dot={false}/><Bar yAxisId="weather" dataKey="rain" fill="#22d3ee" opacity={.5}/></ComposedChart></ResponsiveContainer><div className="ai-chart-legend"><span>● AQI</span><span>● PM2.5</span><span>● Wind</span><span>● Humidity</span><span>▮ Rain</span></div></div>
      </section>
      <section className="ai-section"><div className="ai-section-head"><div><p className="eyebrow">Forecast opportunity</p><h2>Clean Air Window</h2></div><span>Useful sustained periods, not isolated hourly minima</span></div><div className="ai-window-grid"><WindowCard title="Best air window" result={best} accent="#36d399"/><WindowCard title="Highest pollution window" result={worst} accent="#fb7185"/><article className="ai-window-card"><p className="eyebrow">Fastest improvement</p><h3>{improve?`${time(improve.start.time)} → ${time(improve.end.time)}`:"Unavailable"}</h3><strong>{improve?`${num(improve.start.aqi)} → ${num(improve.end.aqi)}`:"—"}</strong><div className="ai-window-aqi"><span>Sustained change</span><b>{improve?.delta??"—"} AQI</b></div></article><article className="ai-window-card"><p className="eyebrow">Fastest deterioration</p><h3>{worsen?`${time(worsen.start.time)} → ${time(worsen.end.time)}`:"Unavailable"}</h3><strong>{worsen?`${num(worsen.start.aqi)} → ${num(worsen.end.aqi)}`:"—"}</strong><div className="ai-window-aqi"><span>Sustained change</span><b>+{worsen?.delta??"—"} AQI</b></div></article></div>
        <div className="ai-strip" aria-label="72-hour air quality strip">{cityData.hours.slice(0,72).map((h,i)=><button key={h.time} title={`${h.time}: AQI ${h.aqi??"unavailable"}`} onClick={()=>{setSelected(i);setRange(72)}} style={{background:h.aqi!=null?getCategoryHex(getAQICategory(h.aqi)):"#263438"}} className={i===selected?"active":""}/>)}</div><div className="ai-strip-labels"><span>NOW</span><span>DAY 1</span><span>DAY 2</span><span>DAY 3</span></div>
      </section>
      <section className="ai-section ai-activity"><div className="ai-section-head"><div><p className="eyebrow">Practical forecast guidance</p><h2>Health & Activity Planner</h2></div><span>Guidance for {shortDate(now.time)} · {time(now.time)}</span></div><p className="ai-activity-intro">Planning suggestions derived locally from the selected hour’s Open-Meteo AQI and weather forecast. They are general guidance, not medical advice.</p><div className="ai-activity-grid">{([{key:"exercise",label:"Outdoor exercise",icon:Activity},{key:"commute",label:"Walking & commute",icon:Bike},{key:"school",label:"School activities",icon:GraduationCap},{key:"ventilation",label:"Home ventilation",icon:House}] as const).map(item=>{const advice=activities[item.key],Icon=item.icon;return <motion.article key={item.key} layout className={`ai-activity-card ${advice.tone}`}><div><Icon size={20}/><span>{item.label}</span></div><strong>{advice.status}</strong><p>{advice.note}</p></motion.article>})}</div>{best&&<button className="ai-best-jump" onClick={()=>{const index=cityData.hours.findIndex(h=>h.time===best.hours[0].time);setRange(72);setSelected(Math.max(0,index));document.querySelector(".ai-playback")?.scrollIntoView({behavior:"smooth"})}}><span>Recommended planning window</span><b>{shortDate(best.hours[0].time)} · {time(best.hours[0].time)}–{time(best.hours.at(-1)!.time)}</b><ArrowRight size={18}/></button>}</section>
      <section className="ai-section"><div className="ai-section-head"><div><p className="eyebrow">Regional context</p><h2>Three-City Snapshot</h2></div></div><div className="ai-city-grid">{initialData.cities.map(c=>{const n=c.hours[0],d=getDominantPollutant(CORE.map(k=>n?.pollutants[k]).filter(Boolean) as any),b=findBestWindow(c.hours.slice(0,72)),t=trend(c.hours.slice(0,24));return <button key={c.city} onClick={()=>chooseCity(c.city)} className={c.city===cityData.city?"active":""}><span>{c.city}</span><strong>{num(n?.aqi)}</strong><em>{n?.aqi!=null?getAQICategory(n.aqi):"Unavailable"}</em><dl><div><dt>Dominant</dt><dd>{d?.label??"—"}</dd></div><div><dt>PM2.5</dt><dd>{num(n?.pollutants.pm2_5?.concentration,1)}</dd></div><div><dt>Best window</dt><dd>{b?`${time(b.hours[0].time)}–${time(b.hours.at(-1)!.time)}`:"—"}</dd></div><div><dt>24h trend</dt><dd>{t.text}</dd></div></dl></button>})}</div></section>
    </motion.div></AnimatePresence>
    <footer className="ai-method"><button onClick={()=>setMethod(v=>!v)}><Info size={14}/> About these insights <ChevronDown size={14}/></button><AnimatePresence>{method&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}><p>All environmental data on this page comes from Open-Meteo. AQI and pollutants originate from its Air Quality API; weather drivers originate from its Weather Forecast API. Dominance uses pollutant-specific U.S. AQI. Explanations are deterministic rules—not another ML model—and associations do not establish causation. Clean Air Window analyzes upcoming hourly AQI. Dispersion Conditions is an app-derived explanatory indicator, not an official meteorological index.</p></motion.div>}</AnimatePresence><p>Weather data by <a href="https://open-meteo.com/" target="_blank">Open-Meteo</a>. Air-quality forecast data: CAMS ENSEMBLE / Copernicus Atmosphere Monitoring Service, via Open-Meteo.</p></footer>
  </div></main>;
}
