"use client";

import { getAQICategory, getCategoryHex } from "@/lib/aqi";
import { formatAQI } from "@/lib/formatters";

interface CityData {
  name: string;
  aqi: number | null;
  xPct: number; // 0–100 % of SVG width
  yPct: number; // 0–100 % of SVG height
}

interface PakistanCityMapProps {
  forecasts: any[];
  observations: any[];
  activeCity: string;
  onSelectCity: (city: string) => void;
}

// ─── Geographic projection ────────────────────────────────────────────────────
// Pakistan bounding box (Natural Earth 1:10m confirmed):
//   Longitude: 60.87°E → 77.84°E  (range 16.97°)
//   Latitude:  23.69°N → 37.10°N  (range 13.41°)
// SVG viewBox: 0 0 200 300
//   x = (lon − 60.87) / 16.97 × 200
//   y = (37.10 − lat) / 13.41 × 300
//
// City coordinates (verified against OpenStreetMap):
//   Karachi:   24.860°N, 67.010°E  → x = 72,  y = 274  → 36 % / 91 %
//   Lahore:    31.550°N, 74.350°E  → x = 159, y = 124  → 80 % / 41 %
//   Islamabad: 33.720°N, 73.060°E  → x = 144, y = 76   → 72 % / 25 %

const SVG_W = 200;
const SVG_H = 300;

const CITY_POSITIONS = [
  { name: "Karachi",   xPct: 36, yPct: 91 },
  { name: "Lahore",    xPct: 80, yPct: 41 },
  { name: "Islamabad", xPct: 72, yPct: 25 },
];

// ─── Accurate Pakistan border (Natural Earth 1:50m) ───────────────────────────
// Source: Natural Earth ne_50m_admin_0_countries.geojson (public domain)
// Processing: 571 raw vertices → Douglas-Peucker ε=0.15° → 93 vertices
// Projected: lon→x via (lon−60.87)/16.97×200, lat→y via (37.10−lat)/13.41×300
// Generated by scripts/generate_pakistan_svg.py
const PAKISTAN_PATH =
  "M 187.4 32.2 L 190.7 44.5 L 185.3 52.9 L 174.9 58.1 L 158.3 52.2 " +
  "L 154.3 54.7 L 153.6 67.7 L 157.7 70.6 L 154.5 75.6 L 156.5 80.4 " +
  "L 154.8 87.5 L 158.9 96.9 L 162.6 97.1 L 162.8 103.0 L 169.3 105.8 " +
  "L 170.4 109.3 L 161.3 118.2 L 162.2 135.7 L 153.6 149.1 L 153.4 155.2 " +
  "L 147.5 160.3 L 142.4 179.2 L 135.2 186.8 L 129.6 204.4 L 117.0 210.1 " +
  "L 112.4 203.0 L 102.1 223.2 L 101.8 231.7 L 109.5 237.8 L 108.8 250.3 " +
  "L 110.7 254.9 L 115.2 255.8 L 119.9 284.1 L 116.0 287.7 L 113.4 283.8 " +
  "L 105.3 289.4 L 93.2 286.0 L 92.6 293.9 L 87.4 294.7 L 85.4 298.6 " +
  "L 78.2 294.4 L 74.3 276.1 L 68.7 273.8 L 68.7 265.6 L 64.3 257.2 " +
  "L 62.0 259.7 L 66.0 260.7 L 46.0 263.8 L 44.7 266.6 L 37.6 261.7 " +
  "L 31.7 262.8 L 30.9 266.0 L 8.2 266.5 L 11.5 243.3 L 18.5 235.8 " +
  "L 27.0 233.8 L 28.7 222.6 L 22.3 220.4 L 22.3 198.1 L 12.0 191.4 " +
  "L 0 162.0 L 18.9 172.1 L 31.8 170.1 L 38.1 172.4 L 41.5 169.0 " +
  "L 49.8 168.7 L 63.2 161.8 L 64.5 140.9 L 70.2 130.6 L 77.6 131.2 " +
  "L 80.9 128.8 L 79.1 125.1 L 85.9 118.5 L 91.1 118.5 L 94.3 122.3 " +
  "L 99.1 115.5 L 101.7 91.3 L 111.0 83.5 L 106.3 69.2 L 115.3 70.4 " +
  "L 120.0 68.2 L 119.0 57.5 L 126.7 42.9 L 121.6 23.7 L 133.0 8.9 " +
  "L 144.3 5.2 L 155.2 6.1 L 161.8 1.4 L 168.2 2.8 L 177.0 11.2 " +
  "L 177.3 23.5 L 180.1 28.4 L 184.8 27.1 Z";

// ─── Label offsets (avoid dot overlap) ───────────────────────────────────────
const LABEL_OFFSETS: Record<string, { x: string; y: string; align: "left" | "right" }> = {
  Karachi:   { x: "calc(36% + 14px)", y: "91%",  align: "left"  },
  Lahore:    { x: "calc(80% + 14px)", y: "41%",  align: "left"  },
  Islamabad: { x: "calc(72% - 82px)", y: "24%",  align: "right" },
};

// ─── Component ────────────────────────────────────────────────────────────────
export default function PakistanCityMap({
  forecasts,
  observations,
  activeCity,
  onSelectCity,
}: PakistanCityMapProps) {
  const cityData: CityData[] = CITY_POSITIONS.map((pos) => {
    const fc  = forecasts?.find((f: any) => f.city === pos.name);
    const obs = observations?.find((o: any) => o.city === pos.name);
    const aqi = obs?.us_aqi ?? fc?.predicted_aqi_24h ?? fc?.forecasts?.["24h"]?.aqi ?? null;
    return { name: pos.name, aqi, xPct: pos.xPct, yPct: pos.yPct };
  });

  return (
    <div className="pakistan-map-wrapper">
      <p className="panel-title" style={{ marginBottom: "12px" }}>Pakistan AQI Overview</p>

      <div
        className="pakistan-map-container"
        style={{ position: "relative", width: "100%", maxWidth: "220px", margin: "0 auto" }}
      >
        {/* SVG map */}
        <svg
          viewBox={`0 0 ${SVG_W} ${SVG_H}`}
          width="100%"
          style={{ display: "block" }}
          aria-hidden="true"
        >
          {/* Country outline */}
          <path
            d={PAKISTAN_PATH}
            fill="rgba(16, 185, 129, 0.05)"
            stroke="rgba(255,255,255,0.15)"
            strokeWidth="1.5"
            strokeLinejoin="round"
          />

          {/* City dots */}
          {cityData.map((city) => {
            const isActive = city.name === activeCity;
            const cat = city.aqi != null ? getAQICategory(Math.round(city.aqi)) : null;
            const hex = cat ? getCategoryHex(cat) : "var(--text-faint)";
            const cx  = (city.xPct / 100) * SVG_W;
            const cy  = (city.yPct / 100) * SVG_H;

            return (
              <g key={city.name}>
                {isActive && (
                  <circle
                    cx={cx} cy={cy} r={14}
                    fill="none"
                    stroke={hex}
                    strokeWidth="1"
                    opacity="0.35"
                  />
                )}
                <circle
                  cx={cx} cy={cy}
                  r={isActive ? 7 : 5}
                  fill={hex}
                  stroke="var(--bg)"
                  strokeWidth="2"
                  style={{ cursor: "pointer" }}
                  onClick={() => onSelectCity(city.name)}
                />
              </g>
            );
          })}
        </svg>

        {/* Absolute-positioned city labels */}
        {cityData.map((city) => {
          const isActive = city.name === activeCity;
          const cat = city.aqi != null ? getAQICategory(Math.round(city.aqi)) : null;
          const hex = cat ? getCategoryHex(cat) : "var(--text-faint)";
          const off = LABEL_OFFSETS[city.name] ?? { x: "50%", y: "50%", align: "left" };

          return (
            <button
              key={city.name}
              onClick={() => onSelectCity(city.name)}
              className="pakistan-city-label"
              style={{
                position:  "absolute",
                left:      off.x,
                top:       off.y,
                textAlign: off.align,
                transform: "translateY(-50%)",
                opacity:   isActive ? 1 : 0.7,
              }}
              aria-label={`${city.name}: AQI ${city.aqi != null ? Math.round(city.aqi) : "unavailable"}`}
            >
              <span style={{ fontSize: "9px", fontWeight: 700, color: "var(--text-muted)", display: "block", letterSpacing: "0.06em", textTransform: "uppercase" }}>
                {city.name}
              </span>
              <span className="tabular" style={{ fontSize: "13px", fontWeight: 800, color: hex, letterSpacing: "-0.02em" }}>
                {formatAQI(city.aqi)}
              </span>
            </button>
          );
        })}
      </div>

      <p style={{ fontSize: "10px", color: "var(--text-faint)", marginTop: "10px", textAlign: "center" }}>
        Click a city to switch dashboard
      </p>
    </div>
  );
}
